version: '1.0'

services:
  database: 
    container_name: 'stock-db'
    image: postgres
    restart: always
    volumes:
      - stock_db:/var/lib/postgresql/data
    ports:
      - 5438:5438
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  webapi:
    container_name: 'stock-api'
    build: 
      context: .
      dockerfile: Dockerfile
    command: bash -c 'npx prisma migrate deploy && npx prisma generate && npm run dev'
    volumes:
      - .:/opt/app:delegated
      - node_modules:/opt/app/node_modules
    ports:
      - ${PORT}:${PORT}
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
    depends_on:
      - database
volumes:
  node_modules:
  stock_db:
    driver: local
